export const siteConfig = {
  name: 'M Murtaza Danish',
  title: 'M Murtaza Danish – Full Stack Developer | Next.js & Node.js Expert',
  description:
    'M Murtaza Danish is a Full Stack Software Engineer based in Islamabad, Pakistan with 3+ years of experience building scalable, production-grade web applications using Next.js, TypeScript, Node.js, PostgreSQL, and modern cloud technologies.',
  url: 'https://mmdanish.com',
  ogImage: '/og-image.png',
  links: {
    github: 'https://github.com/mm-danish',
    linkedin: 'https://linkedin.com/in/mm-danish',
    twitter: 'https://twitter.com/mmdanishdev',
    email: 'mailto:mmdanish.cs@gmail.com',
  },
  keywords: [
    'M Murtaza Danish',
    'mmdanish',
    'Full Stack Developer',
    'Software Engineer Pakistan',
    'Next.js Developer',
    'React Developer',
    'Node.js Developer',
    'TypeScript Engineer',
    'Full Stack Developer Islamabad',
    'Hire Full Stack Developer',
    'Web Developer Pakistan',
    'Next.js',
    'TypeScript',
    'React',
    'Node.js',
    'PostgreSQL',
    'Web Development',
    'Pakistan',
    'Islamabad',
    'Backend Engineer',
    'Frontend Developer',
    'JavaScript Developer',
    'Freelance Developer Pakistan',
  ],
  twitterHandle: '@mmdanishdev',
  author: {
    name: 'M Murtaza Danish',
    location: 'Islamabad, Pakistan',
    role: 'Full Stack Software Engineer',
    experience: '3+ years',
  },
} as const;

